name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]
  delete:
    branches: 
      - "**"
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: workflow info
        run: |
          echo "Main Workflow"
          az version
          az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
          az account show
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_BUSH_0ECB34D10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          production_branch: "main"
          ###### End of Repository/Build Configurations ######
      - name: Static Webapp Url
        run: |
          echo ${{ steps.builddeploy.outputs.static_web_app_url }}
      - name: 'Close Pull Request'
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_BUSH_0ECB34D10 }}
          action: "close"
      - name: 'Pre Delete Branch'
        if: github.event_name == 'delete' && github.event.ref_type == 'branch'
        run: |
          echo "deleted branch:: ${{ github.event.ref }}"
          echo "trying to update redirect_uris..."
          echo "removing uri: ${{ steps.builddeploy.outputs.static_web_app_url }}"
      - name: 'Delete Branch'
        if: github.event_name == 'delete' && github.event.ref_type == 'branch'
        run: |
          az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
          az staticwebapp environment list --name pmn-test-static-web
          echo "deleting preview environment..."
          az staticwebapp environment delete --name pmn-test-static-web --environment-name ${{ github.event.ref }} --yes -y
