name: new-azure-static-web-app-test

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]
  delete:
    branches: 
      - "**"
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_NAME: main1
      STATIC_WEB_APP_NAME: pmn-test-static-web
      APPLICATION_OBJECT_ID: da2a6e83-bee5-4764-8a00-0939678a5829
    name: Build and Deploy Job
    steps:
      - name: workflow info
        run: |
          echo "--- workflow info:: $WORKFLOW_NAME"
          echo "--- subscription info::"
          az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
          az account show
          echo "--- event info::"
          echo "+ event_name:: ${{ github.event_name }}"
          echo "+ event action:: ${{ github.event.action }}"
          echo "+ event ref type:: ${{ github.event.ref_type }}"
          
          APP_AUTH_URL=($(az rest --method GET --uri 'https://graph.microsoft.com/v1.0/applications/da2a6e83-bee5-4764-8a00-0939678a5829' | jq '.web | .redirectUris[]'))
          echo "--- redirectUris: ${APP_AUTH_URL[@]}"
          
          target_source_branch="test-001"
          
          echo "- testing jq... $target_source_branch"
          test_filter=$(az staticwebapp environment list --name pmn-test-static-web | jq --arg sb $target_source_branch '.[] | select(.sourceBranch==$sb) | .name' --raw-output)
          echo $test_filter
          
          echo "--- all preview envivonment..."
          az staticwebapp environment list --name pmn-test-static-web
          
          echo "--- deleting preview environment..."
          build_ids=($(az staticwebapp environment list --name pmn-test-static-web | jq '.[] | .buildId'))
          source_branches=($(az staticwebapp environment list --name pmn-test-static-web | jq '.[] | .sourceBranch'))
          
          echo "------------find build"
          for i in "${!build_ids[@]}";
          do
            echo "+ checking:: build_id: ${build_ids[$i]} - source_branch: ${source_branches[$i]} - target_source_branch: $target_source_branch"
            if [[ ${source_branches[$i]} == \"$target_source_branch\" ]];
            then
              echo "++ found:: build_id:: ${build_ids[$i]}"
              break
            fi
          done
      - name: testing remove callback
        run: |          
          target_source_branch="test-abc"
          target_host_name=($(az staticwebapp environment list --name pmn-test-static-web | jq --arg sb $target_source_branch '.[] | select(.sourceBranch==$sb) | .hostname'))
          
          echo "- target_host_name1:: $target_host_name"
          
          target_host_name=("\"https://$target_host_name/.auth/login/aad/callback\"")
          
          echo "- target_host_name:: $target_host_name"
          
          az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
          APP_AUTH_URL=($(az rest --method GET --uri 'https://graph.microsoft.com/v1.0/applications/da2a6e83-bee5-4764-8a00-0939678a5829' | jq '.web | .redirectUris[]'))
          echo "- curent redirectUris: ${APP_AUTH_URL[@]}"
          for i in "${!APP_AUTH_URL[@]}";
          do
            echo "+ checking:: ${APP_AUTH_URL[$i]} - with:: $target_host_name"
            if [[ ${APP_AUTH_URL[$i]} == $target_host_name ]];
            then
              echo "++ found:: removing:: ${APP_AUTH_URL[$i]}"
              unset 'APP_AUTH_URL[i]'
              break
            fi
          done
          WEB_REDIRECT_URIS=`echo $(echo ${APP_AUTH_URL[@]}) | tr ' ' ','`
          echo "- new redirectUris: $WEB_REDIRECT_URIS"
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        if: github.event_name != 'delete' && github.event.ref_type != 'branch'
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_BUSH_0ECB34D10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          production_branch: "main"
          #deployment_environment: "mytestenv"
          ###### End of Repository/Build Configurations ######
      - name: Static Webapp Url
        run: |
          echo ${{ steps.builddeploy.outputs.static_web_app_url }}
          echo "NEW_WEB_REDIRECT_URIS=${{ steps.builddeploy.outputs.static_web_app_url }}/.auth/login/aad/callback" >> $GITHUB_ENV
      - name: 'Close Pull Request'
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_BUSH_0ECB34D10 }}
          action: "close"
      - name: 'On Branch Deployment'
        if: github.event_name == 'push'
        run: |
          echo "- github.event.ref:: ${{ github.event.ref }}"
          echo "- github.event.ref_type:: ${{ github.event.ref_type }}"
          az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
          APP_AUTH_URL=($(az rest --method GET --uri 'https://graph.microsoft.com/v1.0/applications/da2a6e83-bee5-4764-8a00-0939678a5829' | jq '.web | .redirectUris[]'))
          echo "- curent redirectUris: ${APP_AUTH_URL[@]}"
          
          if [[ ! " ${APP_AUTH_URL[@]} " =~ "\"${{ steps.builddeploy.outputs.static_web_app_url }}/.auth/login/aad/callback\"" ]]; then
            APP_AUTH_URL+=("\"${{ steps.builddeploy.outputs.static_web_app_url }}/.auth/login/aad/callback\"")
            WEB_REDIRECT_URIS=`echo $(echo ${APP_AUTH_URL[@]}) | tr ' ' ','`
            echo "- new redirectUris: $WEB_REDIRECT_URIS"
          else
            echo "- app registration already have the web redirect uris"
          fi
      - name: 'Delete Branch New - Delete Preview Environment'
        if: github.event_name == 'delete' && github.event.ref_type == 'branch'
        run: |
          az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
          az staticwebapp environment list --name pmn-test-static-web
          echo "- deleting preview environment..."
          build_ids=($(az staticwebapp environment list --name pmn-test-static-web | jq '.[] | .buildId'))
          source_branches=($(az staticwebapp environment list --name pmn-test-static-web | jq '.[] | .sourceBranch'))
          target_source_branch=${{ github.event.ref }}
          echo "------------find build"
          for i in "${!build_ids[@]}";
          do
            echo "+ checking:: build_id: ${build_ids[$i]} - source_branch: ${source_branches[$i]} - target_source_branch: $target_source_branch"
            if [[ ${source_branches[$i]} == \"$target_source_branch\" ]];
            then
              echo "++ found:: build_id:: ${build_ids[$i]}"
              result=${build_ids[$i]}
              target_name=(`echo $result | awk '{print substr($0,2,length($0)-2)}'`)
              echo "++ target_name:: $target_name"
            fi
          done
      - name: 'Delete Branch - Remove Callback'
        if: github.event_name == 'delete' && github.event.ref_type == 'branch'
        run: |
          echo "-- github.event.ref:: ${{ github.event.ref }}"
          echo "-- github.event.ref_type:: ${{ github.event.ref_type }}"
          echo "-- removing uri: ${{ env.NEW_WEB_REDIRECT_URIS }}"
          
          target_source_branch=${{ github.event.ref }}
          target_host_name=($(az staticwebapp environment list --name pmn-test-static-web | jq --arg sb $target_source_branch '.[] | select(.sourceBranch==$sb) | .hostname')
          
          target_host_name=("\"https://$target_host_name/.auth/login/aad/callback\"")
          
          az login --service-principal -u ${{ secrets.CLIENT_ID }} -p ${{ secrets.CLIENT_SECRET }} --tenant ${{ secrets.TENANT_ID }}
          APP_AUTH_URL=($(az rest --method GET --uri 'https://graph.microsoft.com/v1.0/applications/da2a6e83-bee5-4764-8a00-0939678a5829' | jq '.web | .redirectUris[]'))
          echo "- curent redirectUris: ${APP_AUTH_URL[@]}"
          for i in "${!APP_AUTH_URL[@]}";
          do
            echo "+ checking:: ${APP_AUTH_URL[$i]} - with:: $target_host_name"
            if [[ ${APP_AUTH_URL[$i]} == $target_host_name ]];
            then
              echo "++ found:: removing:: ${APP_AUTH_URL[$i]}"
              unset 'APP_AUTH_URL[i]'
              break
            fi
          done
          WEB_REDIRECT_URIS=`echo $(echo ${APP_AUTH_URL[@]}) | tr ' ' ','`
          echo "- new redirectUris: $WEB_REDIRECT_URIS"
