name: Azure Static Web Apps CI/CD

on:
  workflow_dispatch:
  push:
    branches: [main, testing, feature/*]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]
  delete:
    branches: [testdelete]
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: workflow info
        run: |
          echo "Main Workflow"
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_BUSH_0ECB34D10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          production_branch: "main"
          ###### End of Repository/Build Configurations ######
      - name: Static Webapp Url
        run: |
          echo ${{ steps.builddeploy.outputs.static_web_app_url }}
      - name: 'Close Pull Request'
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_YELLOW_BUSH_0ECB34D10 }}
          action: "close"
      - name: 'Delete Branch'
        if: github.event_name == 'delete'
        run: |
          echo "GITHUB_SHA is ${{ github.sha }}"
          echo "GITHUB_REF is ${{ github.ref }}"
          echo "${{ github.event.ref }} - ${{ github.event.ref_type }}"
